# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - jobs: buildJob
      steps:
      - bash: echo "Do the Job"
  - stage: DevDeploy
    jobs:
    - deployment: Dev
      environment: DevDeployJob
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "deploy to Dev"
    - stage: QADeploy
    jobs:
    - deployment: QA
      environment: QADeployJob
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "deploy to QA"

- script: echo Runnig on $(operatingSystem)
  displayName: 'Run a one-line script'
